dist: trusty
addons:
  apt:
    packages:
      - libproj-dev
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5.3
  - 2.4.4
  - 2.3.8
matrix:
  include:
    - dist: focal
      rvm: 2.7
  allow_failures:
    - dist: focal
